package Project2.common;

public enum PayloadType {
    CONNECT, DISCONNECT, MESSAGE, START_GAME, CREATE_ROOM, READY, 
    CLIENT_ID, GET_ROOMS, JOIN_ROOM, SYNC_CLIENT, PHASE, RESET_USER_LIST, 
    CHOICE
}